#!/bin/sh

#
# Poor man's display manager
#

SESSION=/usr/bin/nulldm-runx

DISPLAY=:0
SERVER=/usr/bin/Xfbdev
SERVER_ARGS=

if [ -f /etc/default/nulldm ]; then
    . /etc/default/nulldm
fi

PIDFILE=/var/run/nulldm.pid
echo $$ > $PIDFILE

# Setup user's environment
HOME=$(getent passwd | cut -d: -f6)
export HOME

# FIXME: kill xinit in more intelligent way
trap_exit() {
    RETVAL=$?
    killall xinit
    exit $RETVAL
}
trap trap_exit HUP PIPE INT QUIT TERM

while :; do
    xinit $SESSION -- $SERVER $DISPLAY $SERVER_ARGS
done
